


function Ap(){
    window.location.href = "../LAYER1/DEATH/LOST.HTML";
}





// I AM ME AND ME IS YOU.
    // COME PRAY DOWN TO REPENT FOR WHAT IS DUE, FROM THE DEATH OF A LOVER TO THE HORRORS YOU HAVE DONE. YOU TWO WILL NEVER REUNITE IN THE GREAT BEYOND.);